//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group9_006_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string UserId { get; set; }
        public System.DateTime DateHired { get; set; }
        public System.DateTime dateFinished { get; set; }
    
        public virtual User User { get; set; }
    }
}
