//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group9_006_iCAREAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group9_006_iCAREDBEntities1 : DbContext
    {
        public Group9_006_iCAREDBEntities1()
            : base("name=Group9_006_iCAREDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<DocMetaData> DocMetaData { get; set; }
        public virtual DbSet<GeoCode> GeoCode { get; set; }
        public virtual DbSet<PatientRecord> PatientRecord { get; set; }
        public virtual DbSet<TreatmentRecord> TreatmentRecord { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<DrugDictionary> DrugDictionary { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<ModificationHistory> ModificationHistory { get; set; }
    }
}
