//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group9_006_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationHistory
    {
        public System.DateTime DateOfModification { get; set; }
        public System.DateTime Description { get; set; }
        public string DocId { get; set; }
        public string UserId { get; set; }
    
        public virtual DocMetaData DocMetaData { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
